<?php
/**
 * AddExtractionsInDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gemina API
 *
 * Extract structured data from invoices and financial documents, then search, aggregate, and chat over everything you've processed. Authenticate with your API key in the `X-API-Key` header; browser-embedded components use short-lived session tokens minted via `POST /v1/sessions/token`. Guides: https://console.gemina.co/docs
 *
 * The version of the OpenAPI document: 1.7.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gemina\Sdk\Model;

use \ArrayAccess;
use \Gemina\Sdk\ObjectSerializer;

/**
 * AddExtractionsInDTO Class Doc Comment
 *
 * @category Class
 * @description Request body for &#x60;&#x60;POST /documents/{document_id}/extractions&#x60;&#x60;.  No file, external id or end-user id: they belong to the document. FileTag is structurally rejected by &#x60;&#x60;UploadExtractionTypeModel&#x60;&#x60;.
 * @package  Gemina\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AddExtractionsInDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AddExtractionsInDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'correction' => 'bool',
        'evaluation' => 'bool',
        'extraction_types' => '\Gemina\Sdk\Model\UploadExtractionTypeEnum[]',
        'include_coordinates' => 'bool',
        'model_type' => '\Gemina\Sdk\Model\ModelType',
        'template_id' => 'string',
        'thinking' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'correction' => null,
        'evaluation' => null,
        'extraction_types' => null,
        'include_coordinates' => null,
        'model_type' => null,
        'template_id' => 'uuid',
        'thinking' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'correction' => true,
        'evaluation' => true,
        'extraction_types' => false,
        'include_coordinates' => true,
        'model_type' => true,
        'template_id' => true,
        'thinking' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'correction' => 'correction',
        'evaluation' => 'evaluation',
        'extraction_types' => 'extractionTypes',
        'include_coordinates' => 'includeCoordinates',
        'model_type' => 'modelType',
        'template_id' => 'templateId',
        'thinking' => 'thinking'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'correction' => 'setCorrection',
        'evaluation' => 'setEvaluation',
        'extraction_types' => 'setExtractionTypes',
        'include_coordinates' => 'setIncludeCoordinates',
        'model_type' => 'setModelType',
        'template_id' => 'setTemplateId',
        'thinking' => 'setThinking'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'correction' => 'getCorrection',
        'evaluation' => 'getEvaluation',
        'extraction_types' => 'getExtractionTypes',
        'include_coordinates' => 'getIncludeCoordinates',
        'model_type' => 'getModelType',
        'template_id' => 'getTemplateId',
        'thinking' => 'getThinking'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('correction', $data ?? [], null);
        $this->setIfExists('evaluation', $data ?? [], null);
        $this->setIfExists('extraction_types', $data ?? [], null);
        $this->setIfExists('include_coordinates', $data ?? [], null);
        $this->setIfExists('model_type', $data ?? [], null);
        $this->setIfExists('template_id', $data ?? [], null);
        $this->setIfExists('thinking', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['extraction_types'] === null) {
            $invalidProperties[] = "'extraction_types' can't be null";
        }
        if ((count($this->container['extraction_types']) < 1)) {
            $invalidProperties[] = "invalid value for 'extraction_types', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets correction
     *
     * @return bool|null
     */
    public function getCorrection()
    {
        return $this->container['correction'];
    }

    /**
     * Sets correction
     *
     * @param bool|null $correction Enable self-correction of the extracted data; defaults to the account setting
     *
     * @return self
     */
    public function setCorrection($correction)
    {
        if (is_null($correction)) {
            array_push($this->openAPINullablesSetToNull, 'correction');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('correction', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['correction'] = $correction;

        return $this;
    }

    /**
     * Gets evaluation
     *
     * @return bool|null
     */
    public function getEvaluation()
    {
        return $this->container['evaluation'];
    }

    /**
     * Sets evaluation
     *
     * @param bool|null $evaluation Enable self-evaluation of the extracted data; defaults to the account setting
     *
     * @return self
     */
    public function setEvaluation($evaluation)
    {
        if (is_null($evaluation)) {
            array_push($this->openAPINullablesSetToNull, 'evaluation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('evaluation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['evaluation'] = $evaluation;

        return $this;
    }

    /**
     * Gets extraction_types
     *
     * @return \Gemina\Sdk\Model\UploadExtractionTypeEnum[]
     */
    public function getExtractionTypes()
    {
        return $this->container['extraction_types'];
    }

    /**
     * Sets extraction_types
     *
     * @param \Gemina\Sdk\Model\UploadExtractionTypeEnum[] $extraction_types Extraction types to add to the existing document
     *
     * @return self
     */
    public function setExtractionTypes($extraction_types)
    {
        if (is_null($extraction_types)) {
            throw new \InvalidArgumentException('non-nullable extraction_types cannot be null');
        }


        if ((count($extraction_types) < 1)) {
            throw new \InvalidArgumentException('invalid length for $extraction_types when calling AddExtractionsInDTO., number of items must be greater than or equal to 1.');
        }
        $this->container['extraction_types'] = $extraction_types;

        return $this;
    }

    /**
     * Gets include_coordinates
     *
     * @return bool|null
     */
    public function getIncludeCoordinates()
    {
        return $this->container['include_coordinates'];
    }

    /**
     * Sets include_coordinates
     *
     * @param bool|null $include_coordinates Return per-field bounding boxes; defaults to the account setting
     *
     * @return self
     */
    public function setIncludeCoordinates($include_coordinates)
    {
        if (is_null($include_coordinates)) {
            array_push($this->openAPINullablesSetToNull, 'include_coordinates');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('include_coordinates', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['include_coordinates'] = $include_coordinates;

        return $this;
    }

    /**
     * Gets model_type
     *
     * @return \Gemina\Sdk\Model\ModelType|null
     */
    public function getModelType()
    {
        return $this->container['model_type'];
    }

    /**
     * Sets model_type
     *
     * @param \Gemina\Sdk\Model\ModelType|null $model_type Extraction model; defaults to the account's configured model
     *
     * @return self
     */
    public function setModelType($model_type)
    {
        if (is_null($model_type)) {
            array_push($this->openAPINullablesSetToNull, 'model_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('model_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['model_type'] = $model_type;

        return $this;
    }

    /**
     * Gets template_id
     *
     * @return string|null
     */
    public function getTemplateId()
    {
        return $this->container['template_id'];
    }

    /**
     * Sets template_id
     *
     * @param string|null $template_id Custom template to extract with; required by (and only valid with) the custom_template type
     *
     * @return self
     */
    public function setTemplateId($template_id)
    {
        if (is_null($template_id)) {
            array_push($this->openAPINullablesSetToNull, 'template_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('template_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['template_id'] = $template_id;

        return $this;
    }

    /**
     * Gets thinking
     *
     * @return bool|null
     */
    public function getThinking()
    {
        return $this->container['thinking'];
    }

    /**
     * Sets thinking
     *
     * @param bool|null $thinking Enable extended reasoning; defaults to the account setting
     *
     * @return self
     */
    public function setThinking($thinking)
    {
        if (is_null($thinking)) {
            array_push($this->openAPINullablesSetToNull, 'thinking');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('thinking', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['thinking'] = $thinking;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


